name: biblioteca_pessoal
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^3.5.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  google_sign_in: ^6.2.1
  get_it: ^7.7.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  firebase_storage: ^12.3.1
  multi_dropdown: ^3.0.1
  custom_rating_bar: ^3.0.0
  provider: ^6.1.2
  http: ^1.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutterando_analysis: ^0.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/login.svg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700